### ISSUE TITLE
Errno::NOERROR 

### ISSUE THREAD

**Issue by abuzzany** [Shopify/bootsnap#195] opened 2018-09-06 16:59 UTC
Hi everyone, today I had this error:

`Errno::NOERROR `
`Success - bs_fetch:atomic_write_cache_file:open`

Backtrace:
```
bootsnap (1.1.7) lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
bootsnap (1.1.7) lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
bootsnap (1.1.7) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
bootsnap (1.1.7) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
activesupport (5.2.0) lib/active_support/dependencies.rb:283:in `block in require'
activesupport (5.2.0) lib/active_support/dependencies.rb:249:in `load_dependency'
activesupport (5.2.0) lib/active_support/dependencies.rb:283:in `require'
activejob (5.2.0) lib/active_job/core.rb:65:in `set'
actionmailer (5.2.0) lib/action_mailer/message_delivery.rb:140:in `enqueue_delivery'
actionmailer (5.2.0) lib/action_mailer/message_delivery.rb:94:in `deliver_later'
```

This happens after use `deliver_later ` of  `ActionMailer`

this is my `bootsnap-compile-cache` directory:
![screen shot 2018-09-06 at 11 59 02](https://user-images.githubusercontent.com/4792866/45172901-4bebf600-b1cc-11e8-9066-4b5f814b871c.png)

**Comment by burke** [comment] 2019-02-20 00:15
terminal kind of looks like macOS? This is really bizarre because it essentially means `open(2)` returned `-1`, but didn't set `errno`. It actually sounds like an OS bug.

I'm going to close this because there's no way we can make any headway debugging this unless we can reproduce, but please reopen if it's still happening or something.

Sorry for not getting to this sooner.

**Closed by burke** 2019-02-20 00:15 UTC
