### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by CodeGradox** [Shopify/bootsnap#198] opened 2018-09-10 12:08 UTC
Hi,

I just got a Segmentation Fault when running bootsnap with ruby on rails in development mode.

The whole stacktrace is very big so I have pasted them into a gists instead.

[Message from console](https://gist.github.com/CodeGradox/94ac9e66c94d397b1183055d1da5e737)

[Message from OSX DiagnosticReports](https://gist.github.com/CodeGradox/b0d5474b6f23ebe68b868ebc3529f7fb)

**Comment by CodeGradox** [comment] 2018-09-10 12:15
Turns out it was a ActiveRecord_Relation which caused it to crash.

**Comment by CodeGradox** [comment] 2018-09-10 12:36
Ok, so I tried to reduce the problem and I got the crash when I ran this:

```
@crash = if true
    User.all
else
    User.where(id: 1)
end
```

If I change the condition to `1 == 1` then it does not crash.
If I remove bootsnap from the gemfile and remove the `require "bootsnap/setup"` from boot.rb then it does not crash either.

**Comment by rafaelfranca** [comment] 2018-09-10 17:11
Duplicate of #188

**Closed by rafaelfranca** 2018-09-10 17:11 UTC
