### ISSUE TITLE
Segfault doing Model.where(field: "value") if false => using Ruby 2.5

### ISSUE THREAD

**Issue by beetlegius** [Shopify/bootsnap#204] opened 2018-10-05 03:04 UTC
Steps to reproduce:

My configuration:
rbenv with ruby 2.5.1p57 and rails 5.2.1

1- Create a new application with `rails new exampleapp`
2- Create a model with `rails g model User name`
3- Migrate the database with `rails db:migrate`
4- Create a route and an action, then put this code inside `User.where(name: 'anything') if false`
5- Navigate to this route and PUM

**Comment by rafaelfranca** [comment] 2018-10-05 20:12
Duplicate of #188

**Closed by rafaelfranca** 2018-10-05 20:12 UTC
