### ISSUE TITLE
Segfault on unreachable code using MRI 2.5.3, Rails 5.2.2 and Rspec 3.8.1

### ISSUE THREAD

**Issue by matssigge** [Shopify/bootsnap#214] opened 2018-12-05 15:09 UTC
I'm getting a segfault which seems to be related to Bootsnap.

I'm running MRI 2.5.3 on a Mac (macOS Mojave 10.14.1). I did the following:

* `gem install rails` (gives 5.2.2)
* `rails new bootsnap_test -T` 
* Add rspec-rails gem to gemfile
* `bundle install`
* `rails g rspec:install`
* `rails g controller Home`
* Add the following (unreachable) code in HomeController
```ruby
    if false
      a(b: 1)
    end
```

* Now, when simply running `rspec` from the command line, I get a segfault, in what appears to be bootsnap/compile_cache/iseq.rb.
* If I remove the line `require 'bootsnap/setup'` from boot.rb, it works fine.
* If I remove the unreachable code, it works. 
* If I remove the keyword parameter from the `a(b: 1)` call, or replace it with a positional parameter, it works.
* If I switch to Ruby 2.4.5, it works.
* It does *not* fail on `rails server`, only `rspec`

I created a repo with the bug easily reproducible, at https://github.com/matssigge/bootsnap_test. Just clone and run rspec.

I've attached a crash log (the output on the command line, not the Mac crash reporter). [crash.log](https://github.com/Shopify/bootsnap/files/2649354/crash.log)

Is there anything else I should do or any other information you might need?

**Comment by rafaelfranca** [comment] 2018-12-05 15:34
Duplicate of #207. This is a bug in Ruby https://bugs.ruby-lang.org/issues/14959. I was pretty sure that it was fixed in 2.5.3, but it seems not. Can you please report there?

**Closed by rafaelfranca** 2018-12-05 15:34 UTC

**Comment by matssigge** [comment] 2018-12-05 15:37
Oops, sorry, I thought I checked all existing segfault issues. 🙄 

I'll report in Ruby instead. Thanks.
