### ISSUE TITLE
LoadError: cannot load such file INSERT_RANDOM_GEM_NAME -- Bootsnap doesn't clear up loadpath-cache by itself after gem updates etc.

### ISSUE THREAD

**Issue by unkn0wn-developer** [Shopify/bootsnap#302] opened 2020-05-08 20:14 UTC
Bootsnap doesn't clear up loadpath-cache by itself after Gemfile changes/gem updates etc.
This causes random LoadError: cannot load such file INSERT_RANDOM_GEM_NAME errors all the time.

Even removing

rvm ruby installation and re-installing it doesn't fix it.
bundle install other bundle commands. Nothing helps it.
'gem pristine --all` doesn't work as well.
because gems are okay and most of the time everything is installed correctly.

Configuration: rvm + ruby + bundler

Only way to get rid of random LoadErrors is deleting the files below IN THE APP.
**-app/tmp/cache/bootsnap-load-path-cache
-app/tmp/cache/bootsnap-compile-cache**
The other solution is to disable bootsnap in `app/config/boot.rb`

We are not supposed to do this manually.

There are issues from couple months ago (#253 ), a year ago 20+ people liked the temporary solution (https://github.com/Shopify/bootsnap/issues/73#issuecomment-423556785) (#268) , and I'm posting this one now. The issues are being closed since I assume no one wants to fix this. Starting from Rails 5.2 bootsnap is installed by default. This should work as expected. It shouldn't break apps.

This still happens with the newest bootsnap 1.4.6, 1.4.5 and pretty much all versions. For some reason, it doesn't clean up the load path cache after new gem installations or updates. I'm not sure the logic behind it but it should clear it up.

Example:

```
LoadError: cannot load such file -- concurrent/map
/usr/local/rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache.rb:52:in `setup'
/usr/local/rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap.rb:25:in `setup'
/usr/local/rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/setup.rb:31:in `<top (required)>'
/apps/radio/config/boot.rb:5:in `require'
/apps/radio/config/boot.rb:5:in `<top (required)>'
/apps/radio/config/application.rb:1:in `require'
/apps/radio/config/application.rb:1:in `<top (required)>'
/apps/radio/Rakefile:5:in `require'
/apps/radio/Rakefile:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
```

**Comment by rafaelfranca** [comment] 2020-05-29 16:20
Could you please investigate why it is not cleaning in your case? We use bootsnap every day in all the applications at Shopify and we can upgrade gems without this problem.

**Comment by dave-oz** [comment] 2020-05-29 17:51
> Could you please investigate why it is not cleaning in your case? We use bootsnap every day in all the applications at Shopify and we can upgrade gems without this problem.

I'm not sure but we are using CentOS 7.7 and 7.8 with rvm.
Is it normal that some of the cache files are owned by root? We kept resetting the permissions back to our webuser to see if it would make a difference but I can't remember the details now. 
The problem is not consistent. It happens randomly. It was too hard reproduce it for that reason. 

Do you know how cache files are treated permission-wise? Maybe I can check our apps again to see what I will find.

**Comment by rafaelfranca** [comment] 2020-06-09 18:34
The cache files should be owned by the same process that executes the application since it is the application that creates the cache files. If you are seeing files being onwed by root maybe it is because root and your webroot are executing operations in the same app?

**Comment by casperisfine** [comment] 2021-02-01 14:23
Closing as non actionable. Feel free to comment or re-open if you get a reproduction script.

**Closed by casperisfine** 2021-02-01 14:23 UTC
