### ISSUE TITLE
Ruby 2.5.1's bug might create segfault while using this gem

### ISSUE THREAD

**Issue by st0012** [Shopify/bootsnap#191] opened 2018-08-24 09:57 UTC
I found a [Ruby's bug](https://bugs.ruby-lang.org/issues/15021) which might cause segfault when using this gem, because it uses the problematic code [here](https://github.com/Shopify/bootsnap/blob/master/lib/bootsnap/compile_cache/iseq.rb#L12).
It's not the gem's issue but users are more likely to hit this bug when using it (like me)

**Comment by rafaelfranca** [comment] 2018-08-24 14:47
Thanks! Duplicate of #188.

**Closed by rafaelfranca** 2018-08-24 14:47 UTC
