### ISSUE TITLE
EOFError: end of buffer reached

### ISSUE THREAD

**Issue by kuahyeow** [Shopify/bootsnap#474] opened 2024-01-31 04:34 UTC
### I made sure the issue is in bootsnap

After disabling bootsnap, the issue now longer appears

### Steps to reproduce

Unfortunately, this only happens reliably with `gdk update` (GitLab tooling). I am working to find a simpler reproduction in https://gitlab.com/gitlab-org/gitlab/-/merge_requests/143230#note_1750589800 

### Actual behavior

The previous version of bootsnap we used as 1.17.0. After the upgrade to 1.18.1, `bundle exec rails db:migrate` started failing with:

```
rake aborted!
EOFError: end of buffer reached
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/dictionary.rb:62:in `initialize'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/dictionary.rb:32:in `new'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/dictionary.rb:32:in `block in entries'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/dictionary.rb:31:in `map'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/dictionary.rb:31:in `entries'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/gitlab_schema_info.rb:123:in `all_table_allows'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/gitlab_schema_info.rb:99:in `add_table_specific_allows'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/gitlab_schema_info.rb:18:in `initialize'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/gitlab_schema_info.rb:28:in `new'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/gitlab_schema_info.rb:28:in `load_file'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database.rb:81:in `block in all_gitlab_schemas'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database.rb:81:in `map'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database.rb:81:in `all_gitlab_schemas'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database.rb:122:in `schemas_to_base_models'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database.rb:262:in `gitlab_schemas_for_connection'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/shared_model.rb:25:in `using_connection'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/each_database.rb:74:in `with_shared_connection'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/each_database.rb:68:in `with_model_connection'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/each_database.rb:31:in `block in each_model_connection'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/each_database.rb:25:in `each_model_connection'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/partitioning.rb:36:in `sync_partitions'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/partitioning.rb:24:in `sync_partitions_ignore_db_error'
/Users/tkuah/code/gdk-ee/gitlab/config/initializers/postgres_partitioning.rb:58:in `<main>'
/Users/tkuah/code/gdk-ee/gitlab/config/environment.rb:7:in `<main>'
<internal:/Users/tkuah/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/tkuah/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Users/tkuah/.rbenv/versions/3.2.3/bin/bundle:25:in `load'
/Users/tkuah/.rbenv/versions/3.2.3/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
ERROR: 'bundle exec rake db:migrate db:test:prepare' failed.

```

If I run it with `--backtrace`, I notice this lines at the top:

```
/Users/tkuah/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.1/lib/bootsnap/compile_cache/yaml.rb:210:in `read'
/Users/tkuah/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.1/lib/bootsnap/compile_cache/yaml.rb:210:in `storage_to_output'
/Users/tkuah/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.1/lib/bootsnap/compile_cache/yaml.rb:232:in `fetch'
/Users/tkuah/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bootsnap-1.18.1/lib/bootsnap/compile_cache/yaml.rb:232:in `load_file'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/dictionary.rb:62:in `initialize'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/dictionary.rb:32:in `new'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/dictionary.rb:32:in `block in entries'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/dictionary.rb:31:in `map'
/Users/tkuah/code/gdk-ee/gitlab/lib/gitlab/database/dictionary.rb:31:in `entries'
```

I suspect something in 1.18.1 has changed relating to `YAML.load_file`. Looking at how Bootsnap [monkey patches YAML](https://github.com/Shopify/bootsnap/blob/main/lib/bootsnap/compile_cache/yaml.rb#L222-L238), it's possible that changes to the bs_fetch function in 1.18.0 might be relate to this bug. https://github.com/Shopify/bootsnap/commit/df6267fdfab784fa7961ca011bfdf49e32398bd8

### System configuration

**Bootsnap version**: 1.18.1

**Ruby version**: `ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [arm64-darwin22]`

**Rails version**: 7.0.8

**Comment by kuahyeow** [comment] 2024-01-31 05:34
I managed to grab a copy of a bad `tmp/cache/bootsnap`, and also a good copy. It's too large, so I am uploading a YAML cache : 

- cache from the good bootsnap cache
- cache from the bad bootsnap cache
- original YAML file

[compile-cache-yaml.zip](https://github.com/Shopify/bootsnap/files/14107586/compile-cache-yaml.zip)

Hope this helps

**Comment by stanhu** [comment] 2024-01-31 07:18
I'm also running into https://github.com/Shopify/bootsnap/issues/471. It does seem like the header is getting corrupted somehow because you can see in the hexdump the length is indeed set to 1:

```
00000020  01 00 00 00 00 00 00 00
```

**Comment by casperisfine** [comment] 2024-01-31 07:38
Thanks. Yes very likely the same root cause than #471. The revalidation must corrupt the cache entry somehow.

If more people are running into it, I think I'll cut another patch release to disable revalidation (or put it behind a flag).

**Comment by casperisfine** [comment] 2024-01-31 07:57
Interesting catch. If that's indeed it, it shouldn't be too hard to produce a test case. 👀 

BTW: I just pushed a `1.18.2` release that make the feature opt-in, and should be released in a few minutes.

**Comment by stanhu** [comment] 2024-01-31 08:08
Thanks. This diff fixes the issue for me:

```diff
diff --git a/ext/bootsnap/bootsnap.c b/ext/bootsnap/bootsnap.c
index 326aade..5a7ddb0 100644
--- a/ext/bootsnap/bootsnap.c
+++ b/ext/bootsnap/bootsnap.c
@@ -115,7 +115,7 @@ static void bs_cache_path(const char * cachedir, const VALUE path, char (* cache
 static int bs_read_key(int fd, struct bs_cache_key * key);
 static enum cache_status cache_key_equal_fast_path(struct bs_cache_key * k1, struct bs_cache_key * k2);
 static int cache_key_equal_slow_path(struct bs_cache_key * current_key, struct bs_cache_key * cached_key, const VALUE input_data);
-static int update_cache_key(struct bs_cache_key *current_key, int cache_fd, const char ** errno_provenance);
+static int update_cache_key(struct bs_cache_key *current_key, uint64_t data_size, int cache_fd, const char ** errno_provenance);
 
 static void bs_cache_key_digest(struct bs_cache_key * key, const VALUE input_data);
 static VALUE bs_fetch(char * path, VALUE path_v, char * cache_path, VALUE handler, VALUE args);
@@ -331,9 +331,10 @@ static int cache_key_equal_slow_path(struct bs_cache_key *current_key,
   return current_key->digest == cached_key->digest;
 }
 
-static int update_cache_key(struct bs_cache_key *current_key, int cache_fd, const char ** errno_provenance)
+static int update_cache_key(struct bs_cache_key *current_key, uint64_t data_size, int cache_fd, const char ** errno_provenance)
 {
   lseek(cache_fd, 0, SEEK_SET);
+  current_key->data_size = data_size;
   ssize_t nwrite = write(cache_fd, current_key, KEY_SIZE);
   if (nwrite < 0) {
       *errno_provenance = "update_cache_key:write";
@@ -803,7 +804,7 @@ bs_fetch(char * path, VALUE path_v, char * cache_path, VALUE handler, VALUE args
       valid_cache = cache_key_equal_slow_path(&current_key, &cached_key, input_data);
       if (valid_cache) {
         if (!readonly) {
-          if (update_cache_key(&current_key, cache_fd, &errno_provenance)) {
+          if (update_cache_key(&current_key, RSTRING_LEN(input_data), cache_fd, &errno_provenance)) {
               exception_message = path_v;
               goto fail_errno;
           }
@@ -965,7 +966,7 @@ bs_precompile(char * path, VALUE path_v, char * cache_path, VALUE handler)
       }
       valid_cache = cache_key_equal_slow_path(&current_key, &cached_key, input_data);
        if (valid_cache) {
-         if (update_cache_key(&current_key, cache_fd, &errno_provenance)) {
+         if (update_cache_key(&current_key, RSTRING_LEN(input_data), cache_fd, &errno_provenance)) {
              goto fail;
          }
       }
```

I wonder if it's simpler to do:

```c
current_key->data_size = current_key->size;
```

**Comment by casperisfine** [comment] 2024-01-31 08:29
Yup, I have what I think is a cleaner patch, but you were right on the money, I'm just writing a proper test case and will open a PR in a few minutes.

Thanks a lot, that was a great catch.

**Closed** 2024-01-31 08:53 UTC
