### ISSUE TITLE
Ruby master is broken with bootsnap

### ISSUE THREAD

**Issue by SamSaffron** [Shopify/bootsnap#132] opened 2018-02-19 21:02 UTC
Ruby 2.6 (master) no longer works with bootsnap leading to segfaults:

```
/home/sam/.rbenv/versions/master/lib/ruby/gems/2.6.0/gems/bootsnap-1.0.0/lib/bootsnap/compile_cache/iseq.rb:12: [BUG] Segmentation fault at 0x00007ffd00002bee
ruby 2.6.0dev (2018-02-19 trunk 62478) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0023 p:---- s:0116 e:000115 CFUNC  :to_binary
c:0022 p:0017 s:0112 e:000111 METHOD /home/sam/.rbenv/versions/master/lib/ruby/gems/2.6.0/gems/bootsnap-1.0.0/lib/bootsnap/compile_cache/iseq.rb:12 [FINISH]
c:0021 p:---- s:0105 e:000104 CFUNC  :fetch
c:0020 p:0044 s:0098 e:000097 METHOD /home/sam/.rbenv/versions/master/lib/ruby/gems/2.6.0/gems/bootsnap-1.0.0/lib/bootsnap/compile_cache/iseq.rb:40 [FINISH]
c:0019 p:---- s:0092 e:000091 CFUNC  :require
c:0018 p:0028 s:0087 e:000086 METHOD /home/sam/.rbenv/versions/master/lib/ruby/gems/2.6.0/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.r
c:0017 p:0009 s:0081 e:000080 BLOCK  /home/sam/.rbenv/versions/master/lib/ruby/gems/2.6.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292
c:0016 p:0049 s:0078 e:000077 METHOD /home/sam/.rbenv/versions/master/lib/ruby/gems/2.6.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258
c:0015 p:0011 s:0072 e:000071 METHOD /home/sam/.rbenv/versions/master/lib/ruby/gems/2.6.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292
c:0014 p:0006 s:0066 e:000065 TOP    /home/sam/.rbenv/versions/master/lib/ruby/gems/2.6.0/gems/railties-5.1.4/lib/rails/command.rb:1 [FINISH]
c:0013 p:---- s:0063 e:000062 CFUNC  :require
c:0012 p:0028 s:0058 e:000057 METHOD /home/sam/.rbenv/versions/master/lib/ruby/gems/2.6.0/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.r
```

**Comment by Fudoshiki** [comment] 2018-02-24 11:32
**ruby-2.6.0-preview1**
```
 [BUG] Segmentation fault at 0x000075180000750b
ruby 2.6.0preview1 (2018-02-24 trunk 62554) [x86_64-darwin17]
```

**Comment by igravious** [comment] 2018-02-27 22:38
**ruby-2.6.0-preview1**

Aborted (core dumped)

[segfault.txt](https://github.com/Shopify/bootsnap/files/1764963/segfault.txt)

**Comment by burke** [comment] 2018-02-28 03:50
I haven't dug into this at all, but it seems like a ruby bug, I don't think anything we're doing around that bit really sets ruby up for failure in any particular way.

**Comment by SamSaffron** [comment] 2018-02-28 04:06
@nobu should we report the above bug to https://bugs.ruby-lang.org/ ?

**Comment by nobu** [comment] 2018-02-28 14:25
Thank you, please report it there.
It reproduced by `./ruby -e 'RubyVM::InstructionSequence.compile_file(ARGV[0]).to_binary' ext/psych/lib/psych/scalar_scanner.rb`.

**Comment by nobu** [comment] 2018-02-28 23:33
The culprit is r61936(ruby/ruby@823a4fe7d1d8ebb6dd62c815dad4d57c01946add).
Reverted it now.
But `load_from_binary` still raises an exception, and under investigation.

**Comment by nobu** [comment] 2018-03-01 00:39
I think it works now, r62617(ruby/ruby@7d34ed6ecb9506847c4c85170d8df351b5678ad0).

**Comment by jules2689** [comment] 2018-03-06 22:23
Since this is fixed on ruby master, closing this issue.
Please re-open if needed!

**Closed by jules2689** 2018-03-06 22:23 UTC

**Comment by schneems** [comment] 2018-03-07 15:56
Thank you @nobu

**Comment by Fudoshiki** [comment] 2018-03-11 20:05
@nobu #139 It's failing again

**Comment by steakknife** [comment] 2018-05-14 21:45
[Backported patch for 2.5.1](https://git.io/vpQKj) includes:
1. ddf295a26f610affd3a22da91852b52594a6477c
2. 484cc6b3bc828a0bb62aebefd7fdc2c86cab4f57 https://bugs.ruby-lang.org/issues/14553

Bootsnap (Ruby) can now successfully compile files like `puts(a: 1) if false` without crashing.
