### ISSUE TITLE
i get unexpected @path error.

### ISSUE THREAD

**Issue by francelwebdev** [Shopify/bootsnap#374] opened 2021-09-28 07:53 UTC
Hello, i get this error when i run rails s . I use ruby 3.0.2 and rails 7.0.0.alpha2.

```
francel@francel-Inspiron-N5010:~/Documents/rails_api$ rails s
/home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/path.rb:103:in to_s': unexpected @path (TypeError)
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/path.rb:103:in stability'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/path.rb:11:in stable?'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/path.rb:41:in entries_and_dirs'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:159:in block (2 levels) in unshift_paths_locked'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:155:in reverse_each'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:155:in block in unshift_paths_locked'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/store.rb:47:in block in transaction'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/store.rb:45:in synchronize'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/store.rb:45:in transaction'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:154:in unshift_paths_locked'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:107:in block in unshift_paths'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:107:in synchronize'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:107:in unshift_paths'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/change_observer.rb:21:in unshift'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/application.rb:339:in add_lib_to_load_path!'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/application.rb:72:in inherited'
from /home/francel/Documents/rails_api/config/application.rb:24:in module:RailsApi'
from /home/francel/Documents/rails_api/config/application.rb:22:in <main>'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in require'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in block in require_with_bootsnap_lfi'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in register'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in require_with_bootsnap_lfi'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in require'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.0.beta3/lib/zeitwerk/kernel.rb:35:in require'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:137:in block in perform'
from internal:kernel:90:in tap'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:134:in perform'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in run'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in invoke_command'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in dispatch'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/command/base.rb:87:in perform'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/command.rb:48:in invoke'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands.rb:18:in '
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in require'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in block in require_with_bootsnap_lfi'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in register'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in require_with_bootsnap_lfi'
from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in require'
from bin/rails:4:in '
```

**Comment by casperisfine** [comment] 2021-09-28 08:06
The underlying bug can be reproed with:

```ruby
>> Pathname.new("/").tap { |p| p.instance_variable_set(:@path, nil) }.to_s
(irb):3:in `to_s': unexpected @path (TypeError)
```

The question being what in your environment might be doing such a thing.

**Comment by Atastor** [comment] 2021-11-02 09:18
Well, another take on this issue: My problems start much later, i.e. when trying to deploy. The following is from the Capistrano log:

`00:23 deploy:assets:precompile
      01 RBENV_ROOT=/usr/local/rbenv RBENV_VERSION=3.0.2 rbenv exec bundle exec rake assets:precompile
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb:20: warning: already initialized constant Pathname::TO_PATH
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:20: warning: previous definition of TO_PATH was here
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb:22: warning: already initialized constant Pathname::SAME_PATHS
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:22: warning: previous definition of SAME_PATHS was here
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb:34: warning: already initialized constant Pathname::SEPARATOR_LIST
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:34: warning: previous definition of SEPARATOR_LIST was here
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb:35: warning: already initialized constant Pathname::SEPARATOR_PAT
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:35: warning: previous definition of SEPARATOR_PAT was here
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb:41: warning: already initialized constant Pathname::ABSOLUTE_PATH
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:41: warning: previous definition of ABSOLUTE_PATH was here
      01 rake aborted!
      01 TypeError: unexpected @path
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/path.rb:103:in `to_s'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/path.rb:103:in `stability'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/path.rb:11:in `stable?'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/path.rb:41:in `entries_and_dirs'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/cache.rb:159:in `block (2 levels) in unshift_paths_locked'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/cache.rb:155:in `reverse_each'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/cache.rb:155:in `block in unshift_paths_locked'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/store.rb:47:in `block in transaction'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/store.rb:45:in `synchronize'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/store.rb:45:in `transaction'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/cache.rb:154:in `unshift_paths_locked'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/cache.rb:107:in `block in unshift_paths'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/cache.rb:107:in `synchronize'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/cache.rb:107:in `unshift_paths'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/change_observer.rb:21:in `unshift'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/application.rb:361:in `add_lib_to_load_path!'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/application.rb:95:in `inherited'
      01 /var/rails/<my-project>/releases/20211102091423/config/application.rb:11:in `<module:DSGVOAbrechnungen>'
      01 /var/rails/<my-project>/releases/20211102091423/config/application.rb:9:in `<top (required)>'
      01 /var/rails/<my-project>/releases/20211102091423/Rakefile:4:in `require_relative'
      01 /var/rails/<my-project>/releases/20211102091423/Rakefile:4:in `<top (required)>'
      01 /var/rails/<my-project>/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
      01 /usr/local/rbenv/versions/3.0.2/bin/bundle:23:in `load'
      01 /usr/local/rbenv/versions/3.0.2/bin/bundle:23:in `<main>'
`

**Comment by casperisfine** [comment] 2021-11-02 09:37
```
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb:20: warning: already initialized constant Pathname::TO_PATH
      01 /usr/local/rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:20: warning: previous definition of TO_PATH was here
```

Hum, your pathname is loaded twice because of https://github.com/rubygems/rubygems/pull/4992, it could be the root cause or not. Either way I'll be closing this because I'm pretty sure it has nothing to do with bootsnap. If you want to prove it, you can set `DISABLE_BOOTSNAP=1`, if the still bug happens it's not a bootsnap bug.

**Closed by casperisfine** 2021-11-02 09:37 UTC

**Comment by Atastor** [comment] 2021-11-02 12:14
Thanks for the pointer!

**Comment by Atastor** [comment] 2021-11-02 17:52
Just for reasons of completeness: I purged all installations of and references to pathname version 0.2 on dev and server; afterwards I was able to deploy again.

No idea, how this version had been installed in the first place; might have been a too careless `gem update`.
